CREATE TABLE CLIENTES
(
    CLI_CODIGO       CHAR(6) NOT NULL,
    CLI_NOME         VARCHAR(30) NOT NULL,
    CLI_EMAIL        VARCHAR(60) NOT NULL,
    CLI_TELEFONE     CHAR(11),
    DT_CADASTRO      TIMESTAMP NOT NULL
                     DEFAULT CURRENT TIMESTAMP,
    DT_ATUALIZACAO   TIMESTAMP NOT NULL
                     DEFAULT CURRENT TIMESTAMP,

    CONSTRAINT PK_CLIENTES
        PRIMARY KEY (CLI_CODIGO),

    CONSTRAINT UK_CLIENTES_EMAIL
        UNIQUE (CLI_EMAIL)
);